### ISSUE TITLE
Resizing Console/Terminal

### ISSUE THREAD

**Issue by Bubobubobubobubo** [codyebberson/wglt#41]
Hi! I am using your library to display ASCII art layed out on an infinite grid. The performance is rock solid, thanks for working on this 👍. My previous attempt was by using the DOM and it went south. 

In my application, the user can move around the grid and the grid takes the whole space of the viewport. The canvas should always take the whole screen, no matter what happens. I would like to allow users to zoom / dezoom into the grid using a keybinding. I haven't found any internal function allowing me to recompute the grid used by the Console/Terminal. I have tried what I could try already:
- changing the `terminal.height` and `terminal.width` on the fly (glitches).
- creating a new instance of the canvas (breaks the page)

Is there anything I am missing?

**Comment by codyebberson** [comment]
Hi @Bubobubobubobubo - sorry for the comically late reply.

WGLT doesn't have anything for resizing a `Terminal` - that would be a pretty expensive operation due to how everything works internally (lots of pre-computed values and pre-allocated buffers).

One thing you could try is picking a maximum value that you expect users to use, and only display the applicable portion.  In your application logic, you could then render to that limited portion of the `terminal`.  If it would be useful, I could whip up a sample app to demonstrate.

**Comment by Bubobubobubobubo** [comment]
Hi! The project has been abandoned because of performances since the last time I have posted. Thanks for your explanations :smile:. You can close this issue as solved if you prefer.
